version: '3'
services:
  php:
    build: php
    tty: true
    volumes:
      - ./source:/var/www/html
    networks:
      - appnet

  nginx:
    build: nginx
    ports:
      - 8081:8081
    volumes:
      - ./source:/var/www/html
    networks:
      - appnet

  db:
    image: mysql:5.7
    volumes:
      - db_data1:/var/lib/mysql
    ports:
      - 32011:3201
    environment:
       MYSQL_ROOT_PASSWORD: 1
       MYSQL_DATABASE: db
       MYSQL_USER: root
       MYSQL_PASSWORD: 1
    networks:
      - appnet

  cache:
    image: redis:latest
    tty: true
    networks:
      - appnet

  fpc:
    image: redis:latest
    tty: true
    networks:
      - appnet

volumes:
  db_data1:
    driver: "local"
    
networks:
  appnet:
    driver: "bridge"
